--liquibase formatted sql

-- Migration: 0006_find_this
-- Creates: find_this table with initial data (captured from manual DB creation)

--changeset system:0006_find_this_table
CREATE TABLE "find_this" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "value" INTEGER DEFAULT 0 NOT NULL,
    "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL
);

--changeset system:0006_find_this_data
INSERT INTO "find_this" ("name", "description", "value") VALUES
('A', 'First test record', 10),
('B', 'Second test record', 42),
('G', 'Third test record', 99),
('D', 'Fourth test record', 7);
